#include "command_help.h"

int command_help(int argc, char **argv, int optind, int flags) {
  printf("crctk - CRC32 Hexstring Toolkit\n"
"Copyright (C) 2014 2ion (dev@2ion.de)\n"
"Usage: %s [-aCcefhnprstuVv] <file>|<file-listing>\n"
"Options:\n"
"-v, --verify\n"
"  Compute CRC32 and compare with the hexstring in the supplied\n"
"  filename. Exit codes: match -- %d, no match -- %d\n"
"-V DB-FILE, --verify-db DB-FILE\n"
"  Check whether the files record in the database still have the\n"
"  same CRC32 checksums\n"
"-x, --prefer-hexstring\n"
"  Supplements -V. For any tagged file, use the hexstring as\n"
"  the reference CRC32\n"
"-c, --calc\n"
"  Compute the CRC32 for the given file, print and exit\n"
"-n, --numerical\n"
"  Supplements -c. Print the CRC32 in decimal\n"
"-C DB-FILE, --create-db DB-FILE\n"
"   For multiple input files, store a checksum DB in DB-FILE\n"
"   The target file will be overwritten if it exists.\n"
"-a, --append\n"
"   Supplements -C. Append to DB-FILE.\n"
"--version\n"
"   Prints version and compilation information.\n"
" -C FILE. for multiple input files, create a checksum listing\n"
"    for use with the -V option. Overwrites the given file.\n"
" -a Supplements -C. Append to the given database file instead\n"
"    of overwriting it.\n"
" -p FILE. Print the contents of a file created by the -C\n"
"    options to stdout.\n"
" -t Tag file with a CRC32 hexstring. Aborts if\n"
"    the filename does already contain a tag.\n"
" -s Supplements -t. strip eventually existing tag\n"
"    and compute a new CRC32 hexstring.\n"
"    Return values: EXIT_SUCCESS: success\n"
"                   EXIT_FAILURE: generic failure\n"
" -r If the file is tagged, remove the tag.\n"
" -e EXPR. Changes the regular expression used to\n"
"    match tags when doing -s|-r to EXPR. Default:\n"
"    [[:punct:]]\\?[[:xdigit:]]\\{8\\}[[:punct:]]\\?\n"
" -h Print this message and exit successfully.\n",
  argv[0], EXIT_SUCCESS, EXIT_FAILURE);
  return EXIT_SUCCESS;
}

