#!/bin/bash

_crctk(){
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=${COMP_WORDS[COMP_CWORD-1]}

  if [[ $cur =~ ^-$ ]] ; then
    COMPREPLY=( $(compgen -W '-a -c -C -d -D -e -h -m -n -p -P -r -R -s -t -v -V -x' -- $cur) )
    return
  elif [[ $cur =~ ^-- ]] ; then
    COMPREPLY=( $(compgen -W '--append --calc --create-db --delete --dot --tag-regex --merge --numerical --print --to-realpath --remove-tag --realpath --strip-tag --tag --verify --verify-db --hexstring --colors --help --version' -- $cur) )
    return
  fi
}

complete -F _crctk crctk
